"""added user, roles, poolrooms table and relatinships

Revision ID: 09410bd713e0
Revises: a743aa6449a8
Create Date: 2022-08-07 12:54:27.135789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09410bd713e0'
down_revision = 'a743aa6449a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
