"""added user, roles, poolrooms table and relatinships

Revision ID: 47e561637175
Revises: 09410bd713e0
Create Date: 2022-08-07 14:46:13.575128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e561637175'
down_revision = '09410bd713e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomspool',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomspool')
    # ### end Alembic commands ###
