"""added profile picture to model user

Revision ID: a743aa6449a8
Revises: 5139a90cd4b5
Create Date: 2022-08-06 23:25:37.428936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a743aa6449a8'
down_revision = '5139a90cd4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
