"""initial setup

Revision ID: ac692825c016
Revises: 
Create Date: 2022-08-17 18:38:14.557067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac692825c016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('profile_image', sa.VARCHAR(length=250), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('room_key', sa.VARCHAR(length=40), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('category', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_key')
    )
    op.create_index(op.f('ix_room_title'), 'room', ['title'], unique=False)
    op.create_table('roomspool',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomspool')
    op.drop_index(op.f('ix_room_title'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('roles')
    op.drop_table('category')
    # ### end Alembic commands ###
